### ISSUE TITLE
[Bug] Strange behavior with right-alt and Word

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#50] opened 2021-12-21 06:06 UTC
In order to activate `editor normal`  with right alt, I have the following line in `.vindrc`:
```
inoremap <ralt> to_edi_normal
```

-- but in Microsoft Word (I haven't tried in other apps) I get very weird behavior once I click `r-alt`. Keys behave differently than before (e.g. typing `shift-T` in `insert mode` inserts the current time instead of capital T).

**Comment by pit-ray** [comment] 2021-12-21 11:24
This is a exactly bug. The cause is that　`to_edi_normal` shut out key messages before the `<ralt>` release is complete. Therefore, `<ralt>` is still pressed, and then `<ralt-shift-t>` is executed. This will be resolved in the next version.

The current workaround is to low-level map `<ralt>` to another key.

```vim
imap <ralt> <f19>.
inoremap <f19> to_edi_normal
```

Thank you.

**Comment by gilbh** [comment] 2021-12-21 13:42
Works great! Thank you!

**Comment by pit-ray** [comment] 2021-12-26 13:17
I found that the problem is not on the win-vind side. It internally releases the `<ralt>` key before `to_edi_normal`, but the target application does not recognize the release behavior due to the message loop. To solve this problem, we maybe implement a delayed release or something.

Therefore, we prevent side effects by low-level mapping as shown above is a must.

Thanks.

**Closed by pit-ray** 2021-12-26 13:17 UTC
Labels: bug

**Comment by gilbh** [comment] 2022-01-04 00:42
I see your point.
